name: Build APK

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
    inputs:
      user_id:
        description: "User ID for API calls"
        required: true
        type: string
      branch:
        description: "Branch to build from"
        required: true
        type: string
        default: "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Signing on
        run: |
          curl -X POST "${{ secrets.API_URL_SIGNING_ON }}" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.API_TOKEN }}" \
            -d '{"user_id":"${{github.event.inputs.user_id}}", "run_id":"${{ github.run_id }}"}'

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.10

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEY_BASE64 }}" > $GITHUB_WORKSPACE/androidaps.keystore.base64
          base64 -d $GITHUB_WORKSPACE/androidaps.keystore.base64 > $GITHUB_WORKSPACE/androidaps.keystore
          rm $GITHUB_WORKSPACE/androidaps.keystore.base64
          echo "Keystore location: $GITHUB_WORKSPACE/androidaps.keystore"
          ls -l $GITHUB_WORKSPACE/androidaps.keystore

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Print Availability Secrets
        run: |
          echo "Available secrets:"
          echo "KEY_BASE64: ${{ secrets.KEY_BASE64 != '' && '✓' || '✗' }}"
          echo "SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS != '' && '✓' || '✗' }}"
          echo "SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD != '' && '✓' || '✗' }}"
          echo "SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD != '' && '✓' || '✗' }}"

      - name: Build Release APK
        run: |
          ./gradlew assembleRelease --stacktrace --info
           -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/androidaps.keystore \
           -Pandroid.injected.signing.store.password=${{ secrets.SIGNING_STORE_PASSWORD }} \
           -Pandroid.injected.signing.key.alias=${{ secrets.SIGNING_KEY_ALIAS }} \
           -Pandroid.injected.signing.key.password=${{ secrets.SIGNING_KEY_PASSWORD }}

      # - name: Generate APK SHA-256
      #   run: |
      #     echo "APK hash:"
      #     sha256sum app/build/outputs/apk/full/release/app-full-release.apk

      - name: Debug Build Output
        run: |
          echo "Current directory:"
          pwd
          echo "Listing build outputs:"
          ls -R app/build/outputs/
          echo "Listing app directory:"
          ls -R app/

      - name: Upload Artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/full/release/app-full-release.apk

      - name: Signing off
        run: |
          curl -X POST "${{ secrets.API_URL_SIGNING_OFF }}" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.API_TOKEN }}" \
            -d '{"user_id":"${{ github.event.inputs.user_id }}", "run_id":"${{ github.run_id }}", "download_url":"${{ steps.upload-artifact.outputs.artifact-url }}"}'

      - name: Send email
        run: |
          curl -X POST "${{ secrets.API_URL_SEND_MAIL }}" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.API_TOKEN }}" \
            -d '{"user_id":"${{github.event.inputs.user_id}}", "run_id":"${{ github.run_id }}"}'
